### ISSUE TITLE
Discussion: Is there a point to keeping the gloo-net client?

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui-leptos#35]
Currently, the `LemmyClient` trait is implemented for both the `awc` client and a placeholder `Fetch` struct which uses `gloo-net`. I take it that the point of the browser client is to be able to make requests from the browser when needed. However, with Leptos's server function feature, I question if this is necessary: browser-side calls of server functions use a stub that uses the browser's native `fetch` API. With this in mind, is there a reason to keep this logic? Stripping it would make the client implementation much simpler.

**Comment by jim-taylor-business** [comment]
it is a fundamental part of the Leptos SSR Hydrate CSR pattern that we are still following so i don't see the need for this.

i don't know if gloo is bundled inside Leptos and is available for use, so we could use that instead of an explicit dependency.

maybe we can focus on fixing existing issues (Navigation) and old features that have been disabled since the client refactoring (PostActivity).

**Comment by jim-taylor-business** [comment]
proxying everything, as we currently are, through the UI server is not a pattern i have seen before and is only nice in Leptos because of SSR and ActionForms.

it is common to progressively enhance to the browser communicating with the server instance as soon as it's possible to take load off the UI server

**Comment by SleeplessOne1917** [comment]
> proxying everything, as we currently are, through the UI server is not a pattern i have seen before and is only nice in Leptos because of SSR and ActionForms.

You are right. Proxying through the UI server is an unnecessary step that will make things needlessly complicated.
